# Generated by Django 6.1.1 on 2026-09-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='검색 키워드')),
                ('filter_prompt', models.TextField(verbose_name='필터링 프롬프트')),
                ('overview_comment', models.TextField(verbose_name='AI 총평 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장 일시')),
            ],
            options={
                'verbose_name': '저장된 뉴스 브리핑',
                'verbose_name_plural': '저장된 뉴스 브리핑 목록',
                'db_table': 'saved_briefings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='뉴스 제목')),
                ('url', models.URLField(max_length=1000, verbose_name='기사 원문 링크')),
                ('pub_date', models.CharField(blank=True, max_length=100, verbose_name='발행 일시')),
                ('selection_reason', models.TextField(verbose_name='AI 선정 이유')),
                ('summary_bullets', models.JSONField(default=list, help_text='3개의 요약 문장을 담은 JSON 배열', verbose_name='핵심 3줄 요약 목록')),
                ('insight', models.TextField(verbose_name='비즈니스 인사이트 및 시사점')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장 일시')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='curation.savedbriefing', verbose_name='소속 브리핑')),
            ],
            options={
                'verbose_name': '기사 요약',
                'verbose_name_plural': '기사 요약 목록',
                'db_table': 'saved_article_summaries',
                'ordering': ['id'],
            },
        ),
    ]
